### ISSUE TITLE
Does angulartics support custom *dimensions*?

### ISSUE THREAD

**Issue by perqa** [luisfarzati/angulartics#289]
Does angulartics support custom dimensions as used in Google Universal Analytics?

Google (https://support.google.com/analytics/answer/2795983?hl=en):

**Custom dimensions are the new custom variables.**
Custom dimensions give you a flexible way to bring additional data into Google Analytics, so you can learn more about how users interact with your content. Custom dimensions should be used in Universal Analytics where custom variables are used in the Classic Analytics ga.js JavaScript library.

**Comment by nobitagit** [comment]
Hi there, I am trying to enable custom dimensions in an app to send the id of logged in users, but I am finding it unexpectedly difficult to understand how to this should be implemented. 

I went through issue #127 thread but couldn't get my code to send any data (apart when testing an hard-coded value just under the Google Analytics code). I am sure I am missing something stupid, so anyone having an example or any pointer would be really helpful for me.

**Comment by nobitagit** [comment]
> I am sure I am missing something stupid

...and indeed I was. 

Just to share my solution in case anyone will ever need it, I solved my issue after installing 'Google Analytics Debugger' extension for Chrome. The problem seems to be that I was sending custom dimensions as a number instead of a string, at least that's the issue the extension reported. Converting the number worked in the end and my data could be successfully sent to Analytics.

**Comment by octavioamu** [comment]
I need to use a variable in the dimensions but could figure how to use it from the controller or somewhere. I can't put it in the bottom of the document with the analytics code because is going to be undefined. until angular loads. 
I think you @nobitagit are working with this too https://davidsimpson.me/2014/04/20/tutorial-send-user-ids-google-analytics/ Please say me if  you could resolve this

**Comment by nobitagit** [comment]
My implementation in one my controllers looks something along these lines:

```js
var gAnalytics = $window.ga,
     userId = loginUser.id.toString();

gAnalytics('set', 'dimension1', userId);
```

Being `ga` a global you can access it anywhere so you can just attach your custom dimension from whichever controller it's handy for you.

**Comment by octavioamu** [comment]
Thanks @nobitagit that was exactly what I need.

**Comment by luisfarzati** [comment]
I think this is solved already, right? Please feel free to reopen otherwise.
